sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ga63qes/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ga63qes/docker-react npm run test